In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('height_weight.csv')
df.head()

  gender     height      weight
0   Male  73.847017  241.893563
1   Male  68.781904  162.310473
2   Male  74.110105  212.740856
3   Male  71.730978  220.042470
4   Male  69.881796  206.349801

In [3]:
df.shape

(10000, 3)

In [4]:
df.height.describe()

count    10000.000000
mean        66.367560
std          3.847528
min         54.263133
25%         63.505620
50%         66.318070
75%         69.174262
max         78.998742
Name: height, dtype: float64

In [5]:
height_q1 = df.height.quantile(0.25)
height_q3 = df.height.quantile(0.75)
height_q3, height_q1

(np.float64(69.1742617268347), np.float64(63.505620481218955))

In [6]:
height_iqr = height_q3 - height_q1
height_iqr

np.float64(5.668641245615746)

In [7]:
height_lowerlimit = height_q1 - 1.5 * height_iqr
height_upperlimit = height_q3 + 1.5 * height_iqr
height_lowerlimit, height_upperlimit

(np.float64(55.00265861279534), np.float64(77.67722359525831))

In [8]:
df_height_outliers = df[(df.height > height_upperlimit) | (df.height < height_lowerlimit)]

In [9]:
#for weights
df.weight.describe()

count    10000.000000
mean       161.440357
std         32.108439
min         64.700127
25%        135.818051
50%        161.212928
75%        187.169525
max        269.989699
Name: weight, dtype: float64

In [10]:
weight_q1 = df.weight.quantile(0.25)
weight_q3 = df.weight.quantile(0.75)
weight_q1, weight_q3

(np.float64(135.8180513055015), np.float64(187.16952486868348))

In [11]:
weight_iqr = weight_q3 - weight_q1
weight_iqr

np.float64(51.35147356318197)

In [12]:
weight_lowerlimit = weight_q1 - 1.5 * weight_iqr
weight_upperlimit = weight_q3 + 1.5 * weight_iqr
weight_lowerlimit, weight_upperlimit

(np.float64(58.79084096072856), np.float64(264.19673521345646))

In [13]:
df_weight_outliers = df[(df.weight < weight_lowerlimit)|(df.weight > weight_upperlimit)]
df_weight_outliers

     gender     height      weight
2014   Male  78.998742  269.989699

In [18]:
df_cleaned = df[~df.index.isin(df_weight_outliers.index) & ~df.index.isin(df_height_outliers.index)]
df_cleaned.shape

(9992, 3)