In [2]:
import pandas as pd

In [3]:
df = pd.read_csv('AB_NYC_2019.csv')
df.shape

(48895, 16)

In [4]:
df.describe()

,id,host_id,latitude,longitude,price,minimum_nights,number_of_reviews,reviews_per_month,calculated_host_listings_count,availability_365
count,4.889500e+04,4.889500e+04,48895.000000,48895.000000,48895.000000,48895.000000,48895.000000,38843.000000,48895.000000,48895.000000
mean,1.901714e+07,6.762001e+07,40.728949,-73.952170,152.720687,7.029962,23.274466,1.373221,7.143982,112.781327
std,1.098311e+07,7.861097e+07,0.054530,0.046157,240.154170,20.510550,44.550582,1.680442,32.952519,131.622289
min,2.539000e+03,2.438000e+03,40.499790,-74.244420,0.000000,1.000000,0.000000,0.010000,1.000000,0.000000
25%,9.471945e+06,7.822033e+06,40.690100,-73.983070,69.000000,1.000000,1.000000,0.190000,1.000000,0.000000
50%,1.967728e+07,3.079382e+07,40.723070,-73.955680,106.000000,3.000000,5.000000,0.720000,1.000000,45.000000
75%,2.915218e+07,1.074344e+08,40.763115,-73.936275,175.000000,5.000000,24.000000,2.020000,2.000000,227.000000
max,3.648724e+07,2.743213e+08,40.913060,-73.712990,10000.000000,1250.000000,629.000000,58.500000,327.000000,365.000000

In [5]:
#taking important columns
df1 = df[["price","minimum_nights","calculated_host_listings_count","availability_365"]]
df1.head()

   price  minimum_nights  calculated_host_listings_count  availability_365
0    149               1                               6               365
1    225               1                               2               355
2    150               3                               1               365
3     89               1                               1               194
4     80              10                               1                 0

In [8]:
df1.price.quantile(0.99)

np.float64(799.0)

In [10]:
max_threshold = df1.price.quantile(0.99)
min_threshold = df1.price.quantile(0.005)

In [8]:
df1[df.price > max_threshold]

       price  minimum_nights  calculated_host_listings_count  availability_365
85       800               1                               1                 7
496     2000              30                              11                 0
662      850               3                               1               249
762     1300               5                               4               297
780      800               4                               1               257
...      ...             ...                             ...               ...
48304   2999              30                               1               222
48305   1999              30                               1               270
48523   1369               1                               1               349
48535   1749               1                               1               303
48839    800               1                               1                23

[474 rows x 4 columns]

In [11]:
df1[df.price < min_threshold]

       price  minimum_nights  calculated_host_listings_count  availability_365
957       20               3                               1               226
2860      10              30                               4               137
3918      25               5                               3               258
3950      18               1                               1                 0
4647      16               2                               1                 9
...      ...             ...                             ...               ...
48312     25              90                               1               190
48486     16               9                               1               322
48832     20               1                               3               363
48867     25               1                               6               338
48868     25               7                               6               365

[229 rows x 4 columns]

In [17]:
df_cleaned = df[(df.price < max_threshold) & (df.price > min_threshold)]
df_cleaned.shape

(48150, 16)